don't fail if @jupyterlab/apputils-extension:announncements can't be disabled

diff --git a/values/templates/binderhub.yaml b/values/templates/binderhub.yaml
--- a/values/templates/binderhub.yaml
+++ b/values/templates/binderhub.yaml
@@ -17,7 +17,7 @@ binderhub:
       BuildExecutor:
         appendix: |
           USER root
-          RUN jupyter labextension disable "@jupyterlab/apputils-extension:announcements"
+          RUN jupyter labextension disable "@jupyterlab/apputils-extension:announcements" || echo "Failed to disable @jupyterlab/apputils-extension:announcements"
           RUN pip install --no-cache-dir {{ range $package := .Values.binderhub.builder.naavre_requirements }}{{ $package | squote }} {{ end }}
           USER ${NB_USER}
 
